name: CI

on: [ 'push', 'pull_request' ]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: lint
    strategy:
      matrix:
        python-version: [ '3.10', '3.11' ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: pip install ruff==0.0.262 pre-commit==3.2.2

      - name: ruff check
        uses: chartboost/ruff-action@v1
        with:
          args: [ '--config', '.ruff.toml' ]

      - name: black formatter
        uses: psf/black@stable
        with:
          options: '--skip-string-normalization --line-length 120'

      - name: pre-commit
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: --all-files --verbose
